authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

dev_1/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('accounts/',
         include(('authapp.urls', 'auth'), namespace='auth')),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),

]

authapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models

# Create your models here.

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'password1',
            'password2',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegisterForm()

    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import datetime
@login_required


def index(request):
    today = datetime.date.today()
    context = {
        'page_title': 'дата',
        'today': today,



    }
    return render(request, 'mainapp/index.html', context)


#def clare(request):
#    hour = datetime.time.hour()
#    context = {
#        'page_title': 'дата',
 #       'hour': hour,



#    }
#    return render(request, 'mainapp/index.html', context)

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}

<h1 style="text-align: center">Авторизация</h1>
<div style="margin-left: 42%; text-align: justify">
    <div class="form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Войти">
            <p><a href="{% url 'auth:register' %}">Зарегистрироваться</a></p>
        </form>
    </div>

</div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}
    <h1 style="text-align: center">Регистрация</h1>
<div style="margin-left: 42%; text-align: justify">
    <div class="form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="buton"
                   value="зарегистрироваться">
        </form>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>показ сегодняшнего дня</title>
</head>
<body>
<nav class="navbar">
    <ul class="navbar-list-ul">
        <li><a href="{% url 'main:index' %}">Главная</a></li>
        {% if user.is_authenticated %}
        <li style="float:right"><a href="{% url 'auth:logout' %}">Выйти</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block content %}

    {{ today }}
    {{ hour }}


{% endblock %}